ControleVeicular.Web/ViewModels/UsuarioViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleVeicular.Web.ViewModels
{
    public class UsuarioViewModel
    {
        [Key]
        public int UsuarioId { get; set; }

        [Required(ErrorMessage = "Preencha o Nome")]
        [MaxLength(100, ErrorMessage = "Máximo de 100 caracteres")]
        [MinLength(10, ErrorMessage = "Mínimo de 10 caracteres")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Preencha o Login")]
        [MaxLength(100, ErrorMessage = "Máximo de 100 caracteres")]
        [MinLength(10, ErrorMessage = "Mínimo de 10 caracteres")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Preencha a Senha")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }

        [Required(ErrorMessage = "Preencha a Confirmação de Senha")]
        [DataType(DataType.Password)]
        [Compare("Senha", ErrorMessage = "Senha e Confirmação de Senha devem ser iguais")]
        [Display(Name = "Confirmação de Senha")]
        public string ConfirmacaoSenha { get; set; }
    }
}

ControleVeicular.Web/Controllers/UsuariosController.cs
using AutoMapper;
using ControleVeicular.Application.Interfaces;
using ControleVeicular.Domain.Entities;
using ControleVeicular.Web.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
namespace ControleVeicular.Web.Controllers
{
    [Authorize]
    public class UsuariosController : BaseController
    {
        private readonly IUsuarioAppService _usuarioApp;
        private readonly IMapper _mapper;

        public UsuariosController(IMapper mapper, IUsuarioAppService usuarioApp)
        {
            _mapper = mapper;
            _usuarioApp = usuarioApp;
        }

        // GET: UsuariosController
        public ActionResult Index()
        {
            var usuarioViewModel = _mapper.Map<IEnumerable<Usuario>, IEnumerable<UsuarioViewModel>>(_usuarioApp.GetAll());

            return View(usuarioViewModel);
        }

        // GET: UsuariosController/Details/5
        public ActionResult Details(int id)
        {
            var usuario = _usuarioApp.GetById(id);
            var usuarioViewModel = _mapper.Map<Usuario, UsuarioViewModel>(usuario);

            return View(usuarioViewModel);
        }

        // GET: UsuariosController/Create

        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        // POST: UsuariosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioViewModel usuario)
        {
            if (ModelState.IsValid)
            {
                var usuarioDomain = _mapper.Map<UsuarioViewModel, Usuario>(usuario);                
                _usuarioApp.Add(usuarioDomain);

                if(usuarioDomain.UsuarioId == 0)
                {
                    Alert("O Login já está em uso!", Enums.Enum.NotificationType.warning);
                    return View(usuario);
                }    

                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: UsuariosController/Edit/5
        public ActionResult Edit(int id)
        {
            var usuario = _usuarioApp.GetById(id);
            var usuarioViewModel = _mapper.Map<Usuario, UsuarioEditViewModel>(usuario);

            return View(usuarioViewModel);
        }

        // POST: UsuariosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UsuarioEditViewModel usuario)
        {
            if (ModelState.IsValid)
            {
                var usuarioDomain = _mapper.Map<UsuarioEditViewModel, Usuario>(usuario);
                _usuarioApp.Update(usuarioDomain);

                return RedirectToAction("Index");
            }

            return View(usuario);
        }

        // GET: UsuariosController/Delete/5
        public ActionResult Delete(int id)
        {
            var usuario = _usuarioApp.GetById(id);
            var usuarioViewModel = _mapper.Map<Usuario, UsuarioViewModel>(usuario);

            return View(usuarioViewModel);
        }

        // POST: UsuariosController/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var usuario = _usuarioApp.GetById(id);
            _usuarioApp.Remove(usuario);

            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(UsuarioLoginViewModel usuario)
        {
            if (ModelState.IsValid)
            {
                var usuarioDomain = new Usuario("", usuario.Login, usuario.Senha);
                var autenticar = _usuarioApp.Autenticar(usuarioDomain);

                if (!autenticar)
                {
                    Alert("Usuário ou senha inválidos!", Enums.Enum.NotificationType.warning);
                    return View();
                }

                var userClaims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, usuario.Login)
                };

                var identity = new ClaimsIdentity(userClaims, "Usuario");
                var userPrincipal = new ClaimsPrincipal(new[] { identity });

                HttpContext.SignInAsync(userPrincipal);

                return RedirectToAction("Index", "Home", new { area = "" });
            }

            return View(usuario);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Logout()
        {
            var login = HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

ControleVeicular.Web/Views/Usuarios/Create.cshtml
@model ControleVeicular.Web.ViewModels.UsuarioViewModel

@{
    ViewBag.Title = "Cadastro de Usuário";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">
                
                <div class="col-lg-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Nome, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Nome, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Login, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Login, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                        </div>
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Senha, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Senha, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                        </div>
                        <div class="row px-3">
                            @Html.LabelFor(model => model.ConfirmacaoSenha, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.ConfirmacaoSenha, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.ConfirmacaoSenha, "", new { @class = "text-danger" })
                        </div>
                        <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Entrar</button> </div>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Já é cadastrado? <a class="text-danger " asp-area="" asp-controller="Usuarios" asp-action="Login">Faça login</a></small> </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ControleVeicular.Web/Views/Usuarios/Edit.cshtml
@model ControleVeicular.Web.ViewModels.UsuarioEditViewModel

@{
    ViewBag.Title = "Editar Usuário";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UsuarioId)

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Nome, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Nome, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Senha, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Senha, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                        </div>
                        <div class="row px-3">
                            @Html.LabelFor(model => model.ConfirmacaoSenha, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.ConfirmacaoSenha, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.ConfirmacaoSenha, "", new { @class = "text-danger" })
                        </div>

                        <div class="row mb-3 px-3">
                            <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Usuarios" asp-action="Index">Voltar</a>
                            <button type="submit" class="btn btn-blue text-center">Salvar</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    }
</div>

ControleVeicular.Web/Views/Usuarios/Index.cshtml
@model IEnumerable<ControleVeicular.Web.ViewModels.UsuarioViewModel>
@{
    ViewBag.Title = "Listagem de Usuários";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-12">

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row mb-3 px-3">
                            <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Usuarios" asp-action="Create">Adicionar</a>
                        </div>

                        <table class="table">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Nome)
                                </th>
                                <th></th>
                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                                    <td align="right">
                                        @Html.ActionLink("Editar", "Edit", new { id = item.UsuarioId }, new { @class = "btn btn-info" })
                                        <button onclick='deletar(this, @item.UsuarioId);' class='btn btn-danger'>Excluir</button>
                                    </td>
                                </tr>

                            }
                        </table>

                    </div>
                </div>
            </div>
        </div>
    
</div>

<script>
    function deletar(btn, id) {
        swal({
            title: 'Você tem certeza?',
            text: 'A exclusão não poderá ser desfeita!',
            icon: "warning",
            buttons: [
                "Não, manter o registro.",
                'Sim, continuar!'
            ],
            dangerMode: true,
        }).then(function (isConfirm) {
            if (isConfirm) {

                $.ajax({
                    url: "Usuarios/Delete",
                    data:
                    {
                        "id": id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: 'Excluído!',
                            text: 'O Usuário foi excluído com sucesso!',
                            icon: 'success'
                        });
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus, errorThrown);
                    }
                });

            } else {
                swal("Oops!", "Operação Cancelada!", "error");
            }
        })
    }
</script>

ControleVeicular.Web/Views/Usuarios/Login.cshtml
@model ControleVeicular.Web.ViewModels.UsuarioLoginViewModel
@{
    ViewData["Title"] = "Acesso ao Sistema";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">
                <div class="col-lg-6">
                    <div class="card1 pb-5">
                        <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="~/images/hero-img.png" class="image" alt="Imagem da Logo do Sistema"> </div>
                    </div>
                </div>

                <div class="col-lg-6">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Login, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Login, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                        </div>
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Senha, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Senha, new { @class = "mb-4" })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                        </div>
                        <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Entrar</button> </div>
                        <div class="row mb-4 px-3"> <small class="font-weight-bold">Ainda não possui uma conta? <a class="text-danger "asp-area="" asp-controller="Usuarios" asp-action="Create">Cadastre-se</a></small> </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>