ControleVeicular.Web/ViewModels/ModeloViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleVeicular.Web.ViewModels
{
    public class ModeloViewModel
    {
        [Key]
        public int ModeloId { get; set; }

        [Required(ErrorMessage = "Preencha o Nome")]
        [MaxLength(150, ErrorMessage = "Máximo de 150 caracteres")]
        [MinLength(1, ErrorMessage = "Mínimo de 1 caracteres")]
        public string Nome { get; set; }
    }
}

ControleVeicular.Web/Controllers/MarcasController.cs
using AutoMapper;
using ControleVeicular.Application.Interfaces;
using ControleVeicular.Domain.Entities;
using ControleVeicular.Web.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;

namespace ControleVeicular.Web.Controllers
{
    [Authorize]
    public class MarcasController : Controller
    {
        private readonly IMarcaAppService _marcaApp;
        private readonly IMapper _mapper;

        public MarcasController(IMapper mapper, IMarcaAppService marcaApp)
        {
            _mapper = mapper;
            _marcaApp = marcaApp;
        }

        // GET: MarcasController
        public ActionResult Index()
        {
            var marcaViewModel = _mapper.Map<IEnumerable<Marca>, IEnumerable<MarcaViewModel>>(_marcaApp.GetAll());

            return View(marcaViewModel);
        }

        // GET: MarcasController/Details/5
        public ActionResult Details(int id)
        {
            var marca = _marcaApp.GetById(id);
            var marcaViewModel = _mapper.Map<Marca, MarcaViewModel>(marca);

            return View(marcaViewModel);
        }

        // GET: MarcasController/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Marcas/Listar
        [HttpGet]
        public JsonResult Listar()
        {
            return Json(_marcaApp.GetAll());
        }

        // POST: MarcasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MarcaViewModel marca)
        {
            if (ModelState.IsValid)
            {
                var marcaDomain = _mapper.Map<MarcaViewModel, Marca>(marca);
                _marcaApp.Add(marcaDomain);

                return RedirectToAction("Index");
            }

            return View(marca);
        }

        // GET: MarcasController/Edit/5
        public ActionResult Edit(int id)
        {
            var marca = _marcaApp.GetById(id);
            var marcaViewModel = _mapper.Map<Marca, MarcaViewModel>(marca);

            return View(marcaViewModel);
        }

        // POST: MarcasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MarcaViewModel marca)
        {
            if (ModelState.IsValid)
            {
                var marcaDomain = _mapper.Map<MarcaViewModel, Marca>(marca);
                _marcaApp.Update(marcaDomain);

                return RedirectToAction("Index");
            }

            return View(marca);
        }

        // GET: MarcasController/Delete/5
        public ActionResult Delete(int id)
        {
            var marca = _marcaApp.GetById(id);
            var marcaViewModel = _mapper.Map<Marca, MarcaViewModel>(marca);

            return View(marcaViewModel);
        }

        // POST: MarcasController/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var marca = _marcaApp.GetById(id);
            _marcaApp.Remove(marca);

            return RedirectToAction("Index");
        }
    }
}

ControleVeicular.Web/Controllers/ModelosController.cs
using AutoMapper;
using ControleVeicular.Application.Interfaces;
using ControleVeicular.Domain.Entities;
using ControleVeicular.Web.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
namespace ControleVeicular.Web.Controllers
{
    [Authorize]
    public class ModelosController : Controller
    {
        private readonly IModeloAppService _modeloApp;
        private readonly IMapper _mapper;

        public ModelosController(IMapper mapper, IModeloAppService modeloApp)
        {
            _mapper = mapper;
            _modeloApp = modeloApp;
        }

        // GET: ModelosController
        public ActionResult Index()
        {
            var modeloViewModel = _mapper.Map<IEnumerable<Modelo>, IEnumerable<ModeloViewModel>>(_modeloApp.GetAll());

            return View(modeloViewModel);
        }

        // GET: ModelosController/Details/5
        public ActionResult Details(int id)
        {
            var modelo = _modeloApp.GetById(id);
            var modeloViewModel = _mapper.Map<Modelo, ModeloViewModel>(modelo);

            return View(modeloViewModel);
        }

        // GET: ModelosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Modelos/Listar
        [HttpGet]
        public JsonResult Listar()
        {
            return Json(_modeloApp.GetAll());
        }

        // POST: ModelosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ModeloViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                var modeloDomain = _mapper.Map<ModeloViewModel, Modelo>(modelo);
                _modeloApp.Add(modeloDomain);

                return RedirectToAction("Index");
            }

            return View(modelo);
        }

        // GET: ModelosController/Edit/5
        public ActionResult Edit(int id)
        {
            var modelo = _modeloApp.GetById(id);
            var modeloViewModel = _mapper.Map<Modelo, ModeloViewModel>(modelo);

            return View(modeloViewModel);
        }

        // POST: ModelosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ModeloViewModel modelo)
        {
            if (ModelState.IsValid)
            {
                var modeloDomain = _mapper.Map<ModeloViewModel, Modelo>(modelo);
                _modeloApp.Update(modeloDomain);

                return RedirectToAction("Index");
            }

            return View(modelo);
        }

        // GET: ModelosController/Delete/5
        public ActionResult Delete(int id)
        {
            var modelo = _modeloApp.GetById(id);
            var modeloViewModel = _mapper.Map<Modelo, ModeloViewModel>(modelo);

            return View(modeloViewModel);
        }

        // POST: ModelosController/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var modelo = _modeloApp.GetById(id);
            _modeloApp.Remove(modelo);
            return RedirectToAction("Index");
        }
    }
}

ControleVeicular.Web/Views/Modelos/Create.cshtml
@model ControleVeicular.Web.ViewModels.ModeloViewModel

@{
    ViewBag.Title = "Cadastro de Modelo";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Nome, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { htmlAttributes = new { @class = "text-danger" } })
                        </div>

                        <div class="row mb-3 px-3">
                            <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Marcas" asp-action="Index">Voltar</a>
                            <button type="submit" class="btn btn-blue text-center">Cadastrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ControleVeicular.Web/Views/Modelos/Edit.cshtml
@model ControleVeicular.Web.ViewModels.ModeloViewModel

@{
    ViewBag.Title = "Editar Modelo";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ModeloId)

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.Nome, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Nome, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                        </div>

                        <div class="row mb-3 px-3">
                            <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Marcas" asp-action="Index">Voltar</a>
                            <button type="submit" class="btn btn-blue text-center">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

ControleVeicular.Web/Views/Modelos/Index.cshtml
@model IEnumerable<ControleVeicular.Web.ViewModels.ModeloViewModel>

@{
    ViewBag.Title = "Listagem de Modelos";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    <div class="card card0 border-0">
        <div class="row d-flex">

            <div class="col-lg-12">

                <div class="card2 card border-0 px-4 py-5">
                    <div class="row mb-3 px-3">
                        <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Modelos" asp-action="Create">Adicionar</a>
                    </div>

                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nome)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Nome)</td>
                                <td align="right">
                                    @Html.ActionLink("Editar", "Edit", new { id = item.ModeloId }, new { @class = "btn btn-info" })
                                    <button onclick='deletar(this, @item.ModeloId);' class='btn btn-danger'>Excluir</button>
                                </td>
                            </tr>

                        }
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

<script>
    function deletar(btn, id) {
        swal({
            title: 'Você tem certeza?',
            text: 'A exclusão não poderá ser desfeita!',
            icon: "warning",
            buttons: [
                "Não, manter o registro.",
                'Sim, continuar!'
            ],
            dangerMode: true,
        }).then(function (isConfirm) {
            if (isConfirm) {

                $.ajax({
                    url: "Modelos/Delete",
                    data:
                    {
                        "id": id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: 'Excluído!',
                            text: 'O Modelo foi excluído com sucesso!',
                            icon: 'success'
                        });
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus, errorThrown);
                    }
                });

            } else {
                swal("Oops!", "Operação Cancelada!", "error");
            }
        })
    }
</script>