ControleVeicular.Web/ViewModels/AnuncioViewModel.cs
using ControleVeicular.Domain.Entities;
using System;
using System.ComponentModel.DataAnnotations;

namespace ControleVeicular.Web.ViewModels
{
    public class AnuncioViewModel
    {
        [Key]       
        public int AnuncioId { get; set; }

        [Display(Name = "Modelo")]
        [Required(ErrorMessage = "Selecione o Modelo")]
        public int ModeloId { get; set; }

        [Display(Name = "Marca")]
        [Required(ErrorMessage = "Selecione a Marca")]
        public int MarcaId { get; set; }

        [Required(ErrorMessage = "Preencha o Ano")]
        [MaxLength(4, ErrorMessage = "Máximo de 4 caracteres")]
        public string Ano { get; set; }
        [Required(ErrorMessage = "Preencha o Valor de Compra")]
        public decimal ValorCompra { get; set; }
        [Required(ErrorMessage = "Preencha o Valor de Venda")]
        public decimal ValorVenda { get; set; }

        [Required(ErrorMessage = "Preencha a Cor")]
        [MaxLength(20, ErrorMessage = "Máximo de 20 caracteres")]
        public string Cor { get; set; }

        [Required(ErrorMessage = "Preencha o Tipo de Combustível")]
        [MaxLength(15, ErrorMessage = "Máximo de 15 caracteres")]
        [Display(Name = "Tipo de Combustível")]
        public string TipoCombustivel { get; set; }
        public DateTime? DataVenda { get; set; }
    }
}

ControleVeicular.Web/Controllers/AnunciosController.cs
using AutoMapper;
using ControleVeicular.Application.Interfaces;
using ControleVeicular.Domain.Entities;
using ControleVeicular.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ControleVeicular.Web.Controllers
{
    [Authorize]
    public class AnunciosController : Controller
    {
        private readonly IAnuncioAppService _anuncioApp;
        private readonly IMapper _mapper;

        public AnunciosController(IMapper mapper, IAnuncioAppService anuncioApp)
        {
            _mapper = mapper;
            _anuncioApp = anuncioApp;
        }

        // GET: AnunciosController
        public ActionResult Index()
        {
            var anuncios = _anuncioApp.GetAll();
            var anuncioViewModel = _mapper.Map<IEnumerable<Anuncio>, IEnumerable<AnuncioViewModel>>(anuncios);

            return View(anuncioViewModel);
        }

        // GET: AnunciosController/Details/5
        public ActionResult Details(int id)
        {
            var anuncio = _anuncioApp.GetById(id);
            var anuncioViewModel = _mapper.Map<Anuncio, AnuncioViewModel>(anuncio);

            return View(anuncioViewModel);
        }

        // GET: AnunciosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AnunciosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AnuncioViewModel anuncio)
        {
            if (ModelState.IsValid)
            {
                var anuncioDomain = _mapper.Map<AnuncioViewModel, Anuncio>(anuncio);
                _anuncioApp.Add(anuncioDomain);

                return RedirectToAction("Index");
            }

            return View(anuncio);
        }

        // GET: AnunciosController/Edit/5
        public ActionResult Edit(int id)
        {
            var anuncio = _anuncioApp.GetById(id);
            var anuncioViewModel = _mapper.Map<Anuncio, AnuncioViewModel>(anuncio);

            return View(anuncioViewModel);
        }

        // POST: AnunciosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnuncioViewModel anuncio)
        {
            if (ModelState.IsValid)
            {
                var anuncioDomain = _mapper.Map<AnuncioViewModel, Anuncio>(anuncio);
                _anuncioApp.Update(anuncioDomain);

                return RedirectToAction("Index");
            }

            return View(anuncio);
        }

        // GET: AnunciosController/Delete/5
        public ActionResult Delete(int id)
        {
            var anuncio = _anuncioApp.GetById(id);
            var anuncioViewModel = _mapper.Map<Anuncio, AnuncioViewModel>(anuncio);

            return View(anuncioViewModel);
        }

        // POST: AnunciosController/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var anuncio = _anuncioApp.GetById(id);
            _anuncioApp.Remove(anuncio);
            return RedirectToAction("Index");
        }
    }
}

ControleVeicular.Web/Views/Anuncios/Create.cshtml
@model ControleVeicular.Web.ViewModels.AnuncioViewModel

@{
    ViewBag.Title = "Cadastro de Anúncio";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.ModeloId, new { @class = "mb-1" })
                            <select asp-for="ModeloId" class="form-control"></select>
                            @Html.ValidationMessageFor(model => model.ModeloId, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.MarcaId, new { @class = "mb-1" })
                            <select asp-for="MarcaId" class="form-control"></select>
                            @Html.ValidationMessageFor(model => model.MarcaId, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.Ano, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.ValorCompra, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.ValorCompra, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ValorCompra, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.ValorVenda, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.ValorVenda, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ValorVenda, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.Cor, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.TipoCombustivel, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.TipoCombustivel, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TipoCombustivel, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.DataVenda, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.DataVenda, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataVenda, "", new { @class = "text-danger" })
                        </div>

                        <div class="row mb-3 px-3">
                            <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Anuncios" asp-action="Index">Voltar</a>
                            <button type="submit" class="btn btn-blue text-center">Cadastrar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<script>
    $(document).ready(function () {
        listarMarcas();
        listarModelos();

    });

    function listarMarcas() {
        return $.ajax({
            url: "/Marcas/Listar/",
            type: "GET",
            success: function (response) {
                console.log(response);
                $.each(response, function (key, value) {
                    $("#MarcaId").append('<option value=' + value.marcaId + '>' + value.nome + '</option>');
                });
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);

            }
        });
    }

    function listarModelos() {
        return $.ajax({
            url: "/Modelos/Listar/",
            type: "GET",
            success: function (response) {
                console.log(response);
                $.each(response, function (key, value) {
                    $("#ModeloId").append('<option value=' + value.modeloId + '>' + value.nome + '</option>');
                });
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);

            }
        });
    }
</script>

ControleVeicular.Web/Views/Anuncios/Edit.cshtml
@model ControleVeicular.Web.ViewModels.AnuncioViewModel

@{
    ViewBag.Title = "Editar Modelo";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="card card0 border-0">
            <div class="row d-flex">

                <div class="col-lg-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.AnuncioId)
                    @Html.Hidden("MarcaIdAux", Model.MarcaId)
                    @Html.Hidden("ModeloIdAux", Model.ModeloId)

                    <div class="card2 card border-0 px-4 py-5">
                        <div class="row px-3">
                            @Html.LabelFor(model => model.ModeloId, new { @class = "mb-1" })
                            <select asp-for="ModeloId" class="form-control"></select>
                            @Html.ValidationMessageFor(model => model.ModeloId, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.MarcaId, new { @class = "mb-1" })
                            <select asp-for="MarcaId" class="form-control"></select>
                            @Html.ValidationMessageFor(model => model.MarcaId, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.Ano, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Ano, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Ano, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.ValorCompra, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.ValorCompra, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ValorCompra, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.ValorVenda, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.ValorVenda, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ValorVenda, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.Cor, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.Cor, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Cor, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.TipoCombustivel, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.TipoCombustivel, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TipoCombustivel, "", new { @class = "text-danger" })
                        </div>

                        <div class="row px-3">
                            @Html.LabelFor(model => model.DataVenda, new { @class = "mb-1" })
                            @Html.EditorFor(model => model.DataVenda, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DataVenda, "", new { @class = "text-danger" })
                        </div>

                        <div class="row mb-3 px-3">
                            <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Anuncios" asp-action="Index">Voltar</a>
                            <button type="submit" class="btn btn-blue text-center">Salvar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


<script>
    $(document).ready(function () {
        listarMarcas();
        listarModelos();

    });

    function listarMarcas() {
        return $.ajax({
            url: "/Marcas/Listar/",
            type: "GET",
            success: function (response) {
                console.log(response)
                $.each(response, function (key, value) {
                    var selected = "";
                    if (value.marcaId == $("#MarcaIdAux").val()) {
                        selected = "selected";
                    }
                    $("#MarcaId").append('<option ' + selected + ' value=' + value.marcaId + '>' + value.nome + '</option>');
                });
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);

            }
        });
    }

    function listarModelos() {
        return $.ajax({
            url: "/Modelos/Listar/",
            type: "GET",
            success: function (response) {
                $.each(response, function (key, value) {
                    var selected = "";
                    if (value.modeloId == $("#ModeloIdAux").val()) {
                        selected = "selected";
                    }
                    $("#ModeloId").append('<option ' + selected + ' value=' + value.modeloId + '>' + value.nome + '</option>');
                });
            },
            error: function (jqXHR, textStatus, errorThrown) {
                console.log(textStatus, errorThrown);

            }
        });
    }
</script>

ControleVeicular.Web/Views/Anuncios/Index.cshtml
@model IEnumerable<ControleVeicular.Web.ViewModels.AnuncioViewModel>

@{
    ViewBag.Title = "Listagem de Anúncios";
}

<div class="container-fluid px-1 px-md-5 px-lg-1 px-xl-5 py-5 mx-auto">
    <div class="card card0 border-0">
        <div class="row d-flex">

            <div class="col-lg-12">

                <div class="card2 card border-0 px-4 py-5">
                    <div class="row mb-3 px-3">
                        <a class="btn btn-outline-info text-center espaco-botao" asp-area="" asp-controller="Anuncios" asp-action="Create">Adicionar</a>
                    </div>

                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.AnuncioId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ValorVenda)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DataVenda)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.AnuncioId)</td>
                        <td>R$ @Html.DisplayFor(modelItem => item.ValorVenda)</td>
                        <td>@Html.DisplayFor(modelItem => item.DataVenda)</td>
                        <td align="right">
                            @Html.ActionLink("Editar", "Edit", new { id = item.AnuncioId }, new { @class = "btn btn-info" })
                            <button onclick='deletar(this, @item.AnuncioId);' class='btn btn-danger'>Excluir</button>
                        </td>
                    </tr>

                        }
                    </table>

                </div>
            </div>
        </div>
    </div>

</div>

<script>
    function deletar(btn, id) {
        swal({
            title: 'Você tem certeza?',
            text: 'A exclusão não poderá ser desfeita!',
            icon: "warning",
            buttons: [
                "Não, manter o registro.",
                'Sim, continuar!'
            ],
            dangerMode: true,
        }).then(function (isConfirm) {
            if (isConfirm) {

                $.ajax({
                    url: "Anuncios/Delete",
                    data:
                    {
                        "id": id
                    },
                    type: "POST",
                    success: function (response) {
                        swal({
                            title: 'Excluído!',
                            text: 'O Anúncio foi excluído com sucesso!',
                            icon: 'success'
                        });
                        var row = btn.parentNode.parentNode;
                        row.parentNode.removeChild(row);
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log(textStatus, errorThrown);
                    }
                });

            } else {
                swal("Oops!", "Operação Cancelada!", "error");
            }
        })
    }
</script>